source/css/_partial/sidebar.styl
Fix wrongly newlines after dashes. For example, a tag "org-mode".
https://github.com/hexojs/hexo/issues/1092
=> Fix wrongly newlines after dashes.

source/css/style.styl
#main should only float: right for mq-normal if nav-links moved to left column
#main float:right breaks responsive design for mq-tablet and mq-mobile 
(when sidebar is moved to bottom)
Specifically, posts are stuck to the right edge of the screen. If any post contains a codeblock, #main does not resize and results in the screenshot below:
Fix #33
=> Fixed issue preventing #main from resizing when sidebar:left and a post contains a code block

layout/_partial/archive.ejs
In archives page, there is no pagination bar when the page number is
bigger than the configuration value of per_page. This commit fix it.
=> Add pagination bar in archives page

layout/_partial/head.ejs
I assume `Source Code Pro` is for the code highlighting?  So if `highlight:  enable: false` in `_config.yml`, then the unneeded font will not be loaded.  Saves some bandwidth.
If you wish, I can also switch to [jsDelivr CDN](https://github.com/hexojs/hexo-theme-landscape/pull/46) for better performance in China.
=> + switch for font loading

source/css/_variables.styl
see https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide for the implementation details.
Signed-off-by: J Huang <i@jhuang.me>
=> use system-ui font for font-sans

layout/_partial/head.ejs, layout/_partial/header.ejs
This PR fixes an issue that links to the feed are broken unless the root is `/`.
For example, if the url is `example.com`, the root is `/child/` and the path to feed is `/atom.xml`, Hexo generates links ``example.com/atom.xml`` which is incorrect; ``example.com/child/atom.xml`` is corrent.
=> Fix links to the feed

layout/_partial/head.ejs, layout/layout.ejs
The result of `hexo g` immediately after executing `hexo init` is as follows.
```
$ hexo g
$ grep -A 2 -B 2 '</html>' public/index.html
<link rel="stylesheet" href="/css/style.css">
</head>
</html>
<body>
<div id="container">
--
--
</div>
</body>
</html>
```
Tag `</html>` appears twice. The first appears before opening `<body>` tag.
=> Fix closing "html" tag appears twice.

source/css/_partial/article.styl, source/css/_variables.styl, source/js/script.js
This pull request removes "Google+" from the article share button.
The Google+ service ended in April 2019. Therefore, it is necessary to delete it from the share button of the article.
Currently, when Google + 's share button is clicked, the Google+ end announcement page is displayed. Therefore, this button will not be used. So pull request for deletion.
e.g. URL of Google+ share from the demo site of this theme
https://plus.google.com/up/?continue=https://plus.google.com/share?url%3Dhttps://hexo.io/hexo-theme-landscape/hexo-theme-landscape/2013/12/24/long-title/
=> Remove Google+ shared link button because the Google+ service has ended

README.md, _config.yml, layout/_partial/head.ejs
This pull request removes "Google+" from the OGP header tags.
The Google+ service ended in April 2019. Therefore, it is necessary to delete it from the share button of the article.
=> Remove Google+ OGP header tags because the Google+ service has ended

layout/_partial/header.ejs
Makes <Search> placeholder in search form translatable.
=> Make <Search> placeholder in search form translatable.

README.md, _config.yml, source/css/_variables.styl
This pull request resolves Issues #106.
Set the banner image path at the top of the page from the configuration file.
As discussed in Issues #106, it may be better not to make binary changes to the default banner image in user's repository.
Create a new banner image file (e.g., in the `assets` directory) and specify its path from the configuration file.
Thank you.
=> Set the banner image path as a configuration file (resolve #106)

layout/_partial/article.ejs, source/js/script.js
This pull request adds functionality to the Twitter share on the SNS share button below the article.
This pull request will include the article title in the tweet when sharing the article on Twitter.
Currently, only the URL is included in the tweet, not the title of the article.
When the tweet template is displayed, it would be nice to include both the article title and the URL.
Also, when the tweet template is displayed, the article title will be in the selected state. This is a Twitter specification.
It is a function that allows users to easily delete the text written in the template (here, the title of the article).
Please refer to here also about the function of Twitter.
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
Thank you!
=> Include article title in tweets text when sharing with Twitter

README.md
so that commit history is not downloaded to save some space.
=> docs(readme): shallow clone theme

layout/_partial/head.ejs
similar to https://github.com/hexojs/site/pull/1054, which is also load from https://github.com/KyleAMathews/typefaces.
There is official version https://cdn.jsdelivr.net/npm/source-code-pro@2.30.2/source-code-pro.css which is loaded from https://github.com/adobe-fonts/source-code-pro, but the font assets are bigger than google's.
https://github.com/KyleAMathews/typefaces is essentially a mirror of google fonts.
=> fix(highlight-css): load css from jsdelivr cdn

layout/_partial/article.ejs, layout/_partial/post/date.ejs, layout/_partial/post/title.ejs
This fix the `Unspecified type` schema issue identified by [Google](https://search.google.com/structured-data/testing-tool/).
`headline` class is only added to post title in an article, not archive/index.
Add [h-entry](http://microformats.org/wiki/h-entry) Microformat.
schema fix is based on [this example](https://github.com/philwareham/schema-microdata-examples/blob/master/blog.html).
=> fix(seo): use valid schema and add microformat

layout/_partial/archive.ejs
pass `escape` option to paginatorHelper in `https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/paginator.js`
=> fix: HTML entities in paginator without escape

_config.yml
`recent_posts_limits` only affect `widget behavior`. Not content.
=> doc: Move recent_posts_limits to widget behavior block

source/css/_partial/article.styl
This makes `<blockquote>` text unnecessarily larger than the surrounding normal text.
=> Delete unneeded font-size: 1.4em for blockquote

README.md
I might be using hexo / landscape wrong (I only just started), but I installed hexo and landscape, then copied the config from the readme into my `_config.landscape.yml`, and I got the following error (this is the important part of the error I think):
```
/home/caj/files/reps/websites/hexo-blog/nonbinaryalgorithms/node_modules/hexo-theme-landscape/layout/_partial/sidebar.ejs:3
1| <aside id="sidebar"<% if (theme.sidebar === 'bottom'){ %> class="outer"<% } %>>
2|   <% theme.widgets.forEach(function(widget){ %>
>> 3|     <%- partial('_widget/' + widget) %>
4|   <% }) %>
5| </aside>
Partial _widget/archives does not exist. (in _partial/sidebar.ejs)
```
When I had a look, there is no _widget/archives, but there is _widget/archive, and when I fixed that the page could then be built, and I had a …
=> Fix typo in example config

layout/_partial/head.ejs
Fork-Awesome has released 1.2.0 on Aug 2021, but we're still using 1.1.7 released 3 years ago.
=> Update fork-awesome to 1.2.0

layout/_partial/head.ejs
Since now the fork-awesome icons are being used for the mobile navigation toggle buttion, the inclusion of the fork-awesome should not be conditional. If not, the icon won't appear on mobile if you don't configure any links on the theme config, which, as far I as know, is not a required config item.
=> fork-awesome style tag should not be conditional anymore

.github/workflows/deploy.yml
Currently, the landscape theme uses GitHub Pages (https://hexojs.github.io/hexo-theme-landscape/) for publishing previews, but this process requires manual intervention and has not been updated for many years. By switching to GitHub Actions, we can automate the build of the latest preview site.
=> chore: use GitHub actions to deploy preview site

.github/workflows/deploy.yml, README.md, _config.yml
Currently, both the `_config.yml` and `README.md` of the landscape theme contain documentation for some configuration options, but neither is complete. I have moved all the configuration options and their explanations to `_config.yml`, and suggest that users directly copy this file to `_config.landscape.yml`. This way, it is more convenient to configure by referring to the hints inside, compared to consulting the README.
=> docs: update configuration

source/css/_partial/article.styl
Introduced in https://github.com/hexojs/hexo-theme-landscape/commit/7dfe38c6e50b98ad63c51e24cca3f1caf8714870#diff-26213b4007aa6716fd661abe8c9923559eca40f37a5392bca85ccc0b3419389cR59
=> Fix share icon size
