hexojs/hexo-theme-landscape

layout/_partial/head.ejs

I believe you want alternate not alternative http://www.w3.org/TR/html5/links.html#linkTypes

fix rss link tag

---

layout/_partial/archive.ejs

Use the configured archive path

Fix hardcorded archive path

---

_config.yml
layout/_partial/archive.ejs
layout/_partial/footer.ejs
layout/_widget/archive.ejs
layout/_widget/category.ejs
layout/_widget/tag.ejs
source/css/_partial/article.styl
source/css/_partial/sidebar-bottom.styl

1. Expose show_count on article, category, tag widgets as theme.show_count.
1. Expose archive_type on archive widget as theme.archive_type
2. When sidebar is on the bottom:
1. Make the widgets full width
2. Make the lists run horizontally

Improved sidebar behavior

---

languages/nl.yml

I provide a translation into dutch. Some words such tag cloud and powered by are not translated because the translations are rarely used and sound to artificial.

Dutch translation

---

layout/_partial/archive.ejs

the `__(xxx)` syntax wont work within string

translation fix

---

languages/es.yml

Spanish language support

---

README.md

Replaced the hosting URL.
Thanks.

Fix hosting URL

---

_config.yml
layout/_partial/after-footer.ejs
layout/_partial/gauges-analytics.ejs
layout/_partial/head.ejs
package.json

Added [Gaug.es](https://gaug.es) analytics. Moved tracking code to bottom of the page to allow user scripts to load first.
Version bumped :)

Added Gaug.es Realtime analytics. Moved Tracking Code.

---

layout/_partial/archive.ejs

fix pagination prev_text and next_text show text bug.

修复分页prev_text和next_text显示的bug.

---

languages/de.yml

add german language

---

languages/ko.yml

I've added the Korean translation.

add korean language

---

layout/_partial/after-footer.ejs
layout/_partial/head.ejs

This resolves hexojs/hexo-theme-landscape#91

move analytics.js tag to top of <head>

---

source/css/_partial/article.styl
source/css/_variables.styl
source/js/script.js

Added an extra common share option: **LinkedIn**.
Followed existing pattern &:
- Included LinkedIn's Font-Awesome Icon.
- Referenced LinkedIn official color as per their brand guidelines.

Add LinkedIn Share Option.

---

_config.yml
layout/_partial/after-footer.ejs
layout/_partial/article.ejs

add [valine](https://valine.js.org) comment system support.
[![Preview](https://user-images.githubusercontent.com/10877162/33236580-becd8c02-d292-11e7-93fc-8552bbf958bb.png)](https://user-images.githubusercontent.com/10877162/33236580-becd8c02-d292-11e7-93fc-8552bbf958bb.png)

 add valine comment system support

---

layout/_partial/head.ejs

Because a11y -> https://a11yproject.com/posts/never-use-maximum-scale/

[a11y] Remove maximum scale

---

.travis.yml

To make sure PR don't break the theme

Create Travis config

---

layout/_partial/google-analytics.ejs

Fixes the Google Tag Manager issue #109

Used Google's new Tag Manager code

---

source/js/script.js

solve #96, image in link

---

_config.yml

Corrected a spelling mistake.
Maybe it should be "true"?

Corrected a spelling mistake

---

package.json

also update grunt, load-grunt-tasks and grunt-git.
Continue https://github.com/hexojs/hexo-theme-landscape/pull/132

chore(dev-deps): switch to caret versioning update

---

README.md
_config.yml
layout/_widget/recent_posts.ejs

Hi, I think recent_posts_limits need more flexible. So I add this. Please check it.

Add Config:recent_posts_limits

---

languages/tr.yml

I have just translated and added tr.yml

Turkish language has been added

---

languages/zh-CN.yml

The following items has been translated:
- newer
- older
- share
- rss_feed
- category
- tag
The following item was untouched because no need for translation:
- powered_by

complete zh-CN translation

---

scripts/fancybox.js

Issue resolved: https://github.com/hexojs/hexo-theme-landscape/issues/80
Issue resolved: https://github.com/hexojs/hexo-theme-landscape/pull/167

Fix fancybox tag

---

README.md
layout/_partial/header.ejs

I suppose it's a generic case to use subtitle.

refactor: more flexible subtitle

---

README.md
_config.yml
layout/_partial/footer.ejs

Easier to append license in footer

feature: customize copyright

---

README.md

chore: add npm version badge

---

package.json

As is the title.
This package has not been released for a long time.
IMHO we should release a new version with semantic versioning.
Thank you :)

release: v1.0.0

---

layout/_partial/archive.ejs
layout/archive.ejs
layout/category.ejs
layout/index.ejs
layout/tag.ejs

See https://github.com/hexojs/hexo-theme-light/pull/95

feat: remove pagination variable
